### ISSUE TITLE
It fails to format from 'named' style if original SQL text contains time literals.

### ISSUE THREAD

**Issue by ryokash** [cpburnz/python-sql-parameters#4]
### Reproduction Code
    formatter = sqlparams.SQLParams('named', 'qmark')
    formatter.format(
        "select * from T where TM='12:00:00'", {})

### Execution Result
	KeyErrorTraceback (most recent call last)
	<ipython-input-171-76b2b60955c0> in <module>()
	      3 formatter = sqlparams.SQLParams('named', 'qmark')
	      4 formatter.format(
	----> 5 	"select * from T where TM='12:00:00'", {})
	      6 

	c:\usr\lib\python\2.7\x86\lib\site-packages\sqlparams\__init__.pyc in format(self, sql, params)
	    281                 name_to_ords = {}
	    282                 for name in names:
	--> 283                         value = params[name]
	    284                         if isinstance(value, tuple):
	    285                                 ord_params.extend(value)

	KeyError: u'00'

**Comment by cpburnz** [comment]
@ryokash Sorry for the late reply. I seemed to have missed the notification about your report.

Thank you for pointing this out. The bug makes sense because I'm currently doing a naive string substitution without taking the SQL syntax or quotes into consideration.

**Comment by zenwalker** [comment]
It also breaks when type-casting is used

```
In [15]: q.format('SELECT * FROM users WHERE id = :id::int', {'id': '123'})
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-15-2ff1ae9df927> in <module>
----> 1 q.format('SELECT * FROM users WHERE id = :id::int', {'id': '123'})

~/.pyenv/versions/3.8.0/envs/projectname/lib/python3.8/site-packages/sqlparams/__init__.py in format(self, sql, params)
    282                 name_to_ords = {}
    283                 for name in names:
--> 284                         value = params[name]
    285                         if isinstance(value, tuple):
    286                                 ord_params.extend(value)

KeyError: 'int'
```

**Comment by cpburnz** [comment]
Handling for this has been improved for v3. This case now passes.
