### ISSUE TITLE
This lib treat properly sql injection?

### ISSUE THREAD

**Issue by pimtel** [cpburnz/python-sql-parameters#5]
I'm considering using this lib to replace parameters before submitting it to AWS Athena. They didn't implement anything like this in their SDK. So I have a point of concern, this lib treat properly SQL Injection?

Thanks for your time

**Comment by cpburnz** [comment]
@pimtel Sorry about the late response. I seem to have missed the notification about your question.

This library does not concern itself with constructing the query itself. It only performs substitution between parameter styles. So long as the SQL query is constructed in an injection safe manner, the query will remain injection safe using this library. In Python most SQL drivers adhere to the [PEP 249 DB API 2 specification](https://www.python.org/dev/peps/pep-0249/). They provide SQL injection safe methods for executing queries using parameters.
