### ISSUE TITLE
Support for PostgreSQL's $n notation

### ISSUE THREAD

**Issue by zenwalker** [cpburnz/python-sql-parameters#7]
I would like to see the support of native PostgreSQL arguments notation which looks like `$1`, `$2`. Although is not compatible with DB API v2, such notation is used in [asyncpg](https://github.com/MagicStack/asyncpg)—popular asynchronous driver for postgresql. Doesn’t seem to be difficult to implement.

**Comment by cpburnz** [comment]
@zenwalker Adding support for this sounds like a good idea. You're requesting this to be a named parameter style, right? That is, it would convert from the dollar-sign style to one of the ordinal styles?

**Comment by zenwalker** [comment]
No, I think it’s vice-versa. The dollar-sign style is already kind of an ordinal style (basically, the same as `numeric` but with dollar sign instead of colon). And I would prefer to use SQL with named parameters as the input which then will be converted into `$n` notation consumed by asyncpg. Therefore, something like the following:

```
>>> sql, params = query.format("UPDATE users SET age = :age WHERE name = :name", {"name": "Dwalin", "age": 169})
>>> print(sql)
UPDATE users SET age = $1 WHERE name = $2
>>> print(params) 
[169, "Dwalin"]
```

**Comment by zenwalker** [comment]
@cpburnz It seems that I misunderstood the purpose and terminology of the library. I initially thought that it was capable of converting between different styles without restrictions or at least that `numeric` was one of the ordinal styles that could be used as the output.

In this case, my proposal might be against the idea behind this project but still, what do you think about making it possible?

**Comment by cpburnz** [comment]
@zenwalker That makes sense. Adding the dollar-sign style as one of the output ordinal styles sounds reasonable and should be easy. At present it doesn't allow converting from one named style to another because I haven't had the need and no one has requested it yet.

**Comment by cpburnz** [comment]
This is now supported in v3. You can use the parameter styles "numeric_dollar" and "named_dollar".
